name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Linux-x64
      run: dotnet publish -r linux-x64 -c Release -o "release-linux"
    - name: Publish Windows-x64
      run: dotnet publish -r linux-x64 -c Release -o "release-windows"
    - name: Upload Linux Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "steam-login_linux"
        path: "./release-linux"
        if-no-files-found: error
    - name: Upload Windows Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "steam-login_windows"
        path: "./release-windows"
        if-no-files-found: error
